name = "FiniteSizeScaling"
uuid = "fd16a862-e713-4e98-8e8f-513553425ee0"
authors = ["Owen Bradley"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
